language: node_js
node_js:
  - "node"

cache: npm

script: npm run build

deploy:
provider: pages
skip_cleanup: true
github_token: 32c27d2f0e78be8d2ff74a839c1fbd901024ad98
local_dir: dist
on:
  branch: master